# Generated by Django 3.0.5 on 2020-05-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_donortransaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table='donor',
        ),
        migrations.AlterModelTable(
            name='donortransaction',
            table='donor_transaction',
        ),
    ]
